[package]
name = "javascript-runtime-deno"
version = "1.0.0"
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "staticlib"]
name = "javascript_runtime"

[dependencies]
anyhow = { version = "1.0.88" }
deno_core = { version = "0.301.0" }
deno_runtime = { git = 'https://github.com/aidant/deno.git', rev = "dc308a8aa54be65ea4eb596a4d54a4234916affe" }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = { version = "1.0.128" }
serde_v8 = { version = "0.189.0" }
thiserror = { version = "1.0.63" }
tokio = { version = "1.36.0" }
uniffi = { workspace = true }
uuid = { version = "1.10.0", features = ["v4", "serde"] }
