[env]
RUSTY_V8_MIRROR = { value = "https://github.com/aidant/rusty_v8/releases" }

[target.x86_64-linux-android]
linker = "x86_64-linux-android34-clang"

[target.i686-linux-android]
linker = "i686-linux-android34-clang"

[target.armv7-linux-androideabi]
linker = "armv7a-linux-androideabi34-clang"

[target.aarch64-linux-android]
linker = "aarch64-linux-android34-clang"
